feat: add redirect url for object storage
filecoin-project/venus-market pull request #127
Opened 2022-05-09 08:57 UTC by hunjixin

2022-05-24 09:29 UTC, dtynn requested changes

2022-05-24 09:29 UTC, dtynn commented on api/clients/node_client.go
> +			fmt.Println("closerrrr")
这个需要保留么？

2022-05-24 09:29 UTC, dtynn commented on rpc/rpc.go
> +		fmt.Println("xxxxxxxx")
不必保留

2022-05-24 09:35 UTC, hunjixin commented on api/clients/node_client.go
> +			fmt.Println("closerrrr")
已经在最后哪个commit一并删除了

2022-05-24 09:36 UTC, hunjixin commented on rpc/rpc.go
> +		fmt.Println("xxxxxxxx")
已删除

2022-05-24 09:43 UTC, dtynn approved these changes

2022-05-26 02:05 UTC, diwufeiwen approved these changes

2022-05-26 02:06 UTC, merged